config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
 
  resources :doctorappoints
  resources :doctorseeks
  resources :patienttells
  resources :prescriptions
  root "home#index"

  resources :hospitals do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
    resources :doctors do
    end  
  end
  
    get 'doctors/login'
    post 'doctors/signin'
    get 'doctors/logout'
    get 'doctors/doctordiagnosis'
    get 'patients/prescription'
    get 'patients/previousrecords'
    get 'patients/doctorseeks'
    get 'doctors/previousrecords'
    get 'prescriptions/patienttells'

  resources :patients do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital
  has_many :patients , through: :previousrecords
  has_many :patients , through: :doctorappoints
  has_many :patients , through: :prescriptions
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_secure_password
end

app/models/doctorappoint.rb
class Doctorappoint < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  has_many :doctorseeks, dependent: :delete_all
  has_many :patienttells, dependent: :delete_all
end

app/models/doctorseek.rb
class Doctorseek < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors, dependent: :destroy
  has_secure_password
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_secure_password
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_many :doctors , through: :doctorappoints
  has_many :doctors , through: :previousrecords
  has_many :doctors , through: :prescriptions
end

app/models/patienttell.rb
class Patienttell < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/models/previousrecord.rb
class Previousrecord < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def create
        @hospital = Hospital.find(params[:hospital_id])
        @doctor = @hospital.doctors.create(doctor_params)
        redirect_to hospital_path(@hospital)
      end
    def edit
      
    end  

    def new
    end

   
  
    def login
      @doctor = Doctor.new
    end
  
    def logout
      session.delete(:doctor_id)
       redirect_to :controller => 'home', :action => 'index'
    end
  
    def signin
      doctor = Doctor.find_by(email: params[:email])
         if doctor.present? && doctor.authenticate(params[:password])
          session[:doctor_id] = doctor.id
          redirect_to doctors_doctordiagnosis_path(doctor), notice: "Logged in succesfully"
         else
          flash[:alert] = "Invalid email or password"
          render 'login'
         end
    end
    
    def doctordiagnosis
      @doctor = Doctor.find(session[:doctor_id])
      @doctorappoints = Doctorappoint.where(doctor_id: session[:doctor_id])
      # @patient = Patient.find_by(id: @doctorappoint.patient_id)
    end

    def previousrecords
      @doctor = Doctor.find(session[:doctor_id])
      @previousrecords = Previousrecord.where(doctor_id: session[:doctor_id])
      
    end
    
    def index
        @doctors =  Doctor.where(hospital_id: params[:hospital_id])
        @hospital = Hospital.find(session[:hospital_id])
    end
      private
        def doctor_params
          params.require(:doctor).permit(:doctor_name, :address, :department, :qualification,:hospital_name, :dob, :gender, :email, :password, :password_confirmation, :phone)
        end
        def set_doctor
    
          if session[:doctor_id]
            @doctor = Doctor.find(params[:id])
            # current.doctor = doctor.find_by(id: session[:doctor_id])   
            end
        end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:patient_id]
      @patient = Patient.find(session[:patient_id])
    end
    if session[:doctor_id]
      @doctor = Doctor.find(session[:doctor_id])
    end
    if session[:hospital_id]
      @hospital = Hospital.find(session[:hospital_id])
    end
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
    def index
        @patient = Patient.find(params[:patient_id])
        @doctorappoint = Doctorappoint.find(params[:doctorappoint_id])
        @doctor =  Doctor.find(session[:doctor_id])  
    end
    def create
        @prescription = Prescription.new(prescription_params)
        @previous_record = Previousrecord.new(previousrecord_params)
            if @prescription.save
                if @previous_record.save 
                flash[:success] = "/doctor appoint successfully created"
                redirect_to doctors_doctordiagnosis_path
                end
            else
            flash[:error] = "Something went wrong"
            render 'index'
            end
    end
   
    def show
      @doctor =  Doctor.find(session[:doctor_id])
      @patienttells = Patienttell.where(doctorappoint_id: params[:doctorappoint_id])
    end

   

    def destroy
      @prescription = Prescription.find(params[:id])
      @prescription.destroy 
  
      redirect_to patients_prescription_path
    end
    # notes:params[:notes],doctor_id:params[:doctor_id],patient_id:params[:patient_id]
    private
    def prescription_params
      params.permit( :notes, :patient_id,:doctor_id, :doctorName,:image)
    end
    def previousrecord_params
      params.permit( :notes, :patient_id,:doctor_id,:patient_name, :doctorName,:image,:symptoms)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctorappoints_helper.rb
module DoctorappointsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/doctorseeks_helper.rb
module DoctorseeksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/patienttells_helper.rb
module PatienttellsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/previousrecords_helper.rb
module PreviousrecordsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/prescriptions/index.html.erb
<h1>Give Prescription</h1>
<h1 class = "text-dark text-center bg-light" >Doctor Name:<%= @doctor.doctor_name %> </h1>
<h1 class = "text-dark text-center bg-light" >Patient Name:<%= @patient.patient_name %></h1> 
<td><%= link_to 'View More Details', prescriptions_patienttells_path(:doctorappoint_id => @doctorappoint.id),class:"btn btn-primary btn-sm"%></td>

<%= form_with url: prescriptions_path do |form| %>
 
<div class="mb-3">
    
    <%= form.hidden_field :doctor_id, :value => @doctor.id%>
</div>    
<div class="mb-3">

    <%= form.hidden_field :patient_id, :value => @patient.id %>
</div>  
<div class="mb-3">

    <%= form.hidden_field :doctorName, :value => @doctor.doctor_name %>
</div> 
<div class="mb-3">

    <%= form.hidden_field :patient_name, :value => @patient.patient_name %>
</div> 
<div class="mb-3">

    <%= form.hidden_field :symptoms, :value =>@doctorappoint.notes %>
</div> 
<div class="mb-3">
    <%= form.label :notes %>
    <%= form.text_field :notes, class:"form-control", placeholder:"Write the prescription"%>
</div>    
<div class="field mb-3">
    <%= form.label :image %>
    <%= form.file_field :image%>
</div>    
<div class="mb-3">
    <%= form.submit 'submit', class:"btn btn-primary"%>
</div>    
<% end %>

app/views/prescriptions/show.html.erb
<h1>hello Doctor: <%= @doctor.doctor_name%></h1>
<%# <h1>Your Patient <%= @patient.patient_name%></h1> 

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      
        <th>Patient Name</th>
        <th>Notes</th>
         
           

    </tr>
  </thead>

  <tbody>

       <% @patienttells.each do |patienttell| %> 
      <tr>
        
        <td><%= patienttell.patient_name %></td>
        <td><%= patienttell.notes %></td>
       
      

      </tr>
  <% end %>
  
  </tbody>
</table>