config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
 
  resources :doctorappoints
  resources :doctorseeks
  resources :patienttells
  resources :prescriptions
  root "home#index"

  resources :hospitals do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
    resources :doctors do
    end  
  end
  
    get 'doctors/login'
    post 'doctors/signin'
    get 'doctors/logout'
    get 'doctors/doctordiagnosis'
    get 'patients/prescription'
    get 'patients/previousrecords'
    get 'patients/doctorseeks'
    get 'doctors/previousrecords'
    get 'prescriptions/patienttells'

  resources :patients do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital
  has_many :patients , through: :previousrecords
  has_many :patients , through: :doctorappoints
  has_many :patients , through: :prescriptions
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_secure_password
end

app/models/doctorappoint.rb
class Doctorappoint < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  has_many :doctorseeks, dependent: :delete_all
  has_many :patienttells, dependent: :delete_all
end

app/models/doctorseek.rb
class Doctorseek < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors, dependent: :destroy
  has_secure_password
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_secure_password
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_many :doctors , through: :doctorappoints
  has_many :doctors , through: :previousrecords
  has_many :doctors , through: :prescriptions
end

app/models/patienttell.rb
class Patienttell < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/models/previousrecord.rb
class Previousrecord < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def create
        @hospital = Hospital.find(params[:hospital_id])
        @doctor = @hospital.doctors.create(doctor_params)
        redirect_to hospital_path(@hospital)
      end
    def edit
      
    end  

    def new
    end

   
  
    def login
      @doctor = Doctor.new
    end
  
    def logout
      session.delete(:doctor_id)
       redirect_to :controller => 'home', :action => 'index'
    end
  
    def signin
      doctor = Doctor.find_by(email: params[:email])
         if doctor.present? && doctor.authenticate(params[:password])
          session[:doctor_id] = doctor.id
          redirect_to doctors_doctordiagnosis_path(doctor), notice: "Logged in succesfully"
         else
          flash[:alert] = "Invalid email or password"
          render 'login'
         end
    end
    
    def doctordiagnosis
      @doctor = Doctor.find(session[:doctor_id])
      @doctorappoints = Doctorappoint.where(doctor_id: session[:doctor_id])
      # @patient = Patient.find_by(id: @doctorappoint.patient_id)
    end

    def previousrecords
      @doctor = Doctor.find(session[:doctor_id])
      @previousrecords = Previousrecord.where(doctor_id: session[:doctor_id])
      
    end
    
    def index
        @doctors =  Doctor.where(hospital_id: params[:hospital_id])
        @hospital = Hospital.find(session[:hospital_id])
    end
      private
        def doctor_params
          params.require(:doctor).permit(:doctor_name, :address, :department, :qualification,:hospital_name, :dob, :gender, :email, :password, :password_confirmation, :phone)
        end
        def set_doctor
    
          if session[:doctor_id]
            @doctor = Doctor.find(params[:id])
            # current.doctor = doctor.find_by(id: session[:doctor_id])   
            end
        end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:patient_id]
      @patient = Patient.find(session[:patient_id])
    end
    if session[:doctor_id]
      @doctor = Doctor.find(session[:doctor_id])
    end
    if session[:hospital_id]
      @hospital = Hospital.find(session[:hospital_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctorappoints_helper.rb
module DoctorappointsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/doctorseeks_helper.rb
module DoctorseeksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/patienttells_helper.rb
module PatienttellsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/previousrecords_helper.rb
module PreviousrecordsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/home/index.html.erb
<br>



<% if !@patient && !@doctor && !@hospital %>
        <%= link_to 'Hospital Registration', hospitals_path ,class:"btn btn-primary "%>

        &nbsp;

        <%= link_to 'Patient Registration',  {:controller => :patients, :action => :index} ,class:"btn btn-primary "%>
        &nbsp;

        <h2 class="content-subhead">Get Access</h2>
        <p>
            You can login as Hospital by <%= link_to "Clicking Here", {:controller => :hospitals, :action => :login}, { class: 'btn btn-primary'} %>.
            <br/>
            <br/>
            You can login as Doctor by <%= link_to "Clicking Here", {:controller => :doctors, :action => :login}, { class: 'btn btn-primary'} %>.
            <br/>
            <br/>
            You can login as Patient by <%= link_to "Clicking Here", {:controller => :patients, :action => :login}, { class: 'btn btn-primary'} %>.
            
            <br/>
            <code>Have a good day!</code>
        </p>
        <% end %>
        <% if @hospital %>
          <h2 class="content-subhead">You have logged in as <%= @hospital.hospital_name %> <%= link_to "Logout", {:controller => :hospitals, :action => :logout}, { class: 'pure-button  button-secondary'} %> </h2>
          <p>
            Welcome Hospital: &nbsp;<%= @hospital.hospital_name %> Hospital
            You will have the context of the logged in Hospital in viewing all the Hospital related views. Please logout in case you are facing some issues. Have a good health!
          </p>
        <% end %>
        <% if @doctor %>
          <h2 class="content-subhead">You have logged in as Doctor  <%= link_to "Logout", {:controller => :doctors, :action => :logout}, { class: 'pure-button  button-secondary'} %></h2>
          <p>
            Welcome Doctor: <%= @doctor.doctor_name %>&nbsp;<%= @doctor.email %>
            You will have the context of the logged in doctor in viewing all the doctor related views. Please logout in case you are facing some issues. Have a good health!
          </p>
        <% end %>
        <% if @patient %>
          <h2 class="content-subhead">You have logged in as <%= @patient.patient_name %>  <%= link_to "Logout", {:controller => :patients, :action => :logout}, { class: 'pure-button  button-secondary'} %></h2>
          <p>
            Welcome : &nbsp;<%= @patient.email %>
            You will have the context of the logged in Patient in viewing all the Patient related views. Please logout in case you are facing some issues. Have a good health!
          </p>
        <% end %>