config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
 
  resources :doctorappoints
  resources :doctorseeks
  resources :patienttells
  resources :prescriptions
  root "home#index"

  resources :hospitals do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
    resources :doctors do
    end  
  end
  
    get 'doctors/login'
    post 'doctors/signin'
    get 'doctors/logout'
    get 'doctors/doctordiagnosis'
    get 'patients/prescription'
    get 'patients/previousrecords'
    get 'patients/doctorseeks'
    get 'doctors/previousrecords'
    get 'prescriptions/patienttells'

  resources :patients do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital
  has_many :patients , through: :previousrecords
  has_many :patients , through: :doctorappoints
  has_many :patients , through: :prescriptions
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_secure_password
end

app/models/doctorappoint.rb
class Doctorappoint < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  has_many :doctorseeks, dependent: :delete_all
  has_many :patienttells, dependent: :delete_all
end

app/models/doctorseek.rb
class Doctorseek < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors, dependent: :destroy
  has_secure_password
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_secure_password
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_many :doctors , through: :doctorappoints
  has_many :doctors , through: :previousrecords
  has_many :doctors , through: :prescriptions
end

app/models/patienttell.rb
class Patienttell < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/models/previousrecord.rb
class Previousrecord < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def create
        @hospital = Hospital.find(params[:hospital_id])
        @doctor = @hospital.doctors.create(doctor_params)
        redirect_to hospital_path(@hospital)
      end
    def edit
      
    end  

    def new
    end

   
  
    def login
      @doctor = Doctor.new
    end
  
    def logout
      session.delete(:doctor_id)
       redirect_to :controller => 'home', :action => 'index'
    end
  
    def signin
      doctor = Doctor.find_by(email: params[:email])
         if doctor.present? && doctor.authenticate(params[:password])
          session[:doctor_id] = doctor.id
          redirect_to doctors_doctordiagnosis_path(doctor), notice: "Logged in succesfully"
         else
          flash[:alert] = "Invalid email or password"
          render 'login'
         end
    end
    
    def doctordiagnosis
      @doctor = Doctor.find(session[:doctor_id])
      @doctorappoints = Doctorappoint.where(doctor_id: session[:doctor_id])
      # @patient = Patient.find_by(id: @doctorappoint.patient_id)
    end

    def previousrecords
      @doctor = Doctor.find(session[:doctor_id])
      @previousrecords = Previousrecord.where(doctor_id: session[:doctor_id])
      
    end
    
    def index
        @doctors =  Doctor.where(hospital_id: params[:hospital_id])
        @hospital = Hospital.find(session[:hospital_id])
    end
      private
        def doctor_params
          params.require(:doctor).permit(:doctor_name, :address, :department, :qualification,:hospital_name, :dob, :gender, :email, :password, :password_confirmation, :phone)
        end
        def set_doctor
    
          if session[:doctor_id]
            @doctor = Doctor.find(params[:id])
            # current.doctor = doctor.find_by(id: session[:doctor_id])   
            end
        end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:patient_id]
      @patient = Patient.find(session[:patient_id])
    end
    if session[:doctor_id]
      @doctor = Doctor.find(session[:doctor_id])
    end
    if session[:hospital_id]
      @hospital = Hospital.find(session[:hospital_id])
    end
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = Hospital.all
  end

  def show
    @hospital = Hospital.find(params[:id])
  end

  def new
    @hospital = Hospital.new
  end

  def login
    @hospital = Hospital.new
  end

  def logout
    session.delete(:hospital_id)
     redirect_to :controller => 'home', :action => 'index'
  end

  def signin
    hospital = Hospital.find_by(email: params[:email])
       if hospital.present? && hospital.authenticate(params[:password])
        session[:hospital_id] = hospital.id
        redirect_to hospital_path(hospital), notice: "Logged in succesfully"
       else
        flash[:alert] = "Invalid email or password"
        render 'login'
       end
  end

  
  
  def create
    @hospital = Hospital.new(hospital_params)
    if @hospital.save
      flash[:success] = "Hospital successfully created"
      session[:hospital_id] = @hospital.id
      redirect_to @hospital
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @hospital = Hospital.find(params[:id])
  end

  def update
    @hospital = Hospital.find(params[:id])

    if @hospital.update(hospital_params)
      redirect_to @hospital
    else
      render :edit
    end
  end

  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy

    redirect_to root_path
  end

  private
  def hospital_params
    params.require(:hospital).permit(:hospital_name, :address, :email, :password, :password_confirmation, :phone)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctorappoints_helper.rb
module DoctorappointsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/doctorseeks_helper.rb
module DoctorseeksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/patienttells_helper.rb
module PatienttellsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/previousrecords_helper.rb
module PreviousrecordsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/hospitals/_form.html.erb
<%= form_with model: hospital do |form| %>
</br>
   <div class="field form-group">
    
    <%= form.text_field :hospital_name  ,class:"form-control",placeholder:"Hospital name"%>
    <% hospital.errors.full_messages_for(:hospital_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
  <div class="field form-group">
   
    <%= form.text_field :address, class:"form-control" , placeholder:"address"%>
    <% hospital.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
  <div class="field form-group">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
    <% hospital.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
<div class="row">
  <div class="col-md-6">

    <%= form.password_field :password, class:"form-control", placeholder:"password" %>
    <% hospital.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="col-md-6 ">
 
    <%= form.password_field :password_confirmation , class:"form-control", placeholder:"password confirmation"%>
    <% hospital.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  </div>
  </br>
  <div class="field form-group">
   
    <%= form.text_field :phone,  class:"form-control",placeholder:"phone"%>
    <% hospital.errors.full_messages_for(:phone).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
  <div class="actions text-center">
    <%= form.submit nil, class: 'btn btn-success' %>
     
  </div>
 
<% end %>

app/views/hospitals/edit.html.erb
<h1>Edit hospital</h1>

<%= render "form", hospital: @hospital %>

app/views/hospitals/index.html.erb
</br>
<h1 class = "text-light text-center bg-dark">Hospital List</h1>

<div class="hospital_page">

<%= link_to "Add New Hospital", new_hospital_path ,class:"btn btn-secondary btn-lg" %>
</div>
<br>
  <table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      <th>Hospital name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.hospital_name %></td>
        <td><%= hospital.address %></td>
        <td><%= hospital.email %></td>
        <td><%= hospital.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hospitals/login.html.erb
<h1> Hospital Login </h1>
<%= form_with url: signin_hospitals_path do |form| %>

 <div class="mb-3">
    <%= form.label :email%>
    <%= form.text_field :email, class:"form-control", placeholder:"email"%>
</div>    
<div class="mb-3">
    <%= form.label :password%>
    <%= form.password_field :password, class:"form-control", placeholder:"password"%>
</div>    
<div class="mb-3">
    <%= form.submit 'submit', class:"btn btn-primary"%>
</div>    
<% end %>

app/views/hospitals/new.html.erb
</br>
<h1 class = "text-light text-center bg-secondary">Add New hospital</h1>


<%= render "form", hospital: @hospital %>

app/views/hospitals/show.html.erb
<h1 class = "text-light text-center bg-dark"><%= @hospital.hospital_name %> </h1>

<div class="doctor_page">
<%= link_to "Edit hospital profile", edit_hospital_path(@hospital),class:"btn btn-primary btn-lg justify-right" %>
<%= link_to "Display Doctors", hospital_doctors_path(@hospital),class:"btn btn-primary btn-lg justify-right" %>
</div>
<br>
<%# <%= link_to "Add Doctors", new_hospital_doctor_path(@hospital),class:"btn btn-secondary btn-sm" %> 

<h2 class = "text-light text-center bg-secondary">Add Doctor</h2>
<%= render 'doctors/form' %>