config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
 
  resources :doctorappoints
  resources :doctorseeks
  resources :patienttells
  resources :prescriptions
  root "home#index"

  resources :hospitals do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
    resources :doctors do
    end  
  end
  
    get 'doctors/login'
    post 'doctors/signin'
    get 'doctors/logout'
    get 'doctors/doctordiagnosis'
    get 'patients/prescription'
    get 'patients/previousrecords'
    get 'patients/doctorseeks'
    get 'doctors/previousrecords'
    get 'prescriptions/patienttells'

  resources :patients do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital
  has_many :patients , through: :previousrecords
  has_many :patients , through: :doctorappoints
  has_many :patients , through: :prescriptions
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_secure_password
end

app/models/doctorappoint.rb
class Doctorappoint < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  has_many :doctorseeks, dependent: :delete_all
  has_many :patienttells, dependent: :delete_all
end

app/models/doctorseek.rb
class Doctorseek < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors, dependent: :destroy
  has_secure_password
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_secure_password
  has_many :previousrecords, dependent: :destroy
  has_many :doctorappoints, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_many :doctors , through: :doctorappoints
  has_many :doctors , through: :previousrecords
  has_many :doctors , through: :prescriptions
end

app/models/patienttell.rb
class Patienttell < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  belongs_to :doctorappoint
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/models/previousrecord.rb
class Previousrecord < ApplicationRecord
  has_one_attached :image
  belongs_to :patient
  belongs_to :doctor
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def create
        @hospital = Hospital.find(params[:hospital_id])
        @doctor = @hospital.doctors.create(doctor_params)
        redirect_to hospital_path(@hospital)
      end
    def edit
      
    end  

    def new
    end

   
  
    def login
      @doctor = Doctor.new
    end
  
    def logout
      session.delete(:doctor_id)
       redirect_to :controller => 'home', :action => 'index'
    end
  
    def signin
      doctor = Doctor.find_by(email: params[:email])
         if doctor.present? && doctor.authenticate(params[:password])
          session[:doctor_id] = doctor.id
          redirect_to doctors_doctordiagnosis_path(doctor), notice: "Logged in succesfully"
         else
          flash[:alert] = "Invalid email or password"
          render 'login'
         end
    end
    
    def doctordiagnosis
      @doctor = Doctor.find(session[:doctor_id])
      @doctorappoints = Doctorappoint.where(doctor_id: session[:doctor_id])
      # @patient = Patient.find_by(id: @doctorappoint.patient_id)
    end

    def previousrecords
      @doctor = Doctor.find(session[:doctor_id])
      @previousrecords = Previousrecord.where(doctor_id: session[:doctor_id])
      
    end
    
    def index
        @doctors =  Doctor.where(hospital_id: params[:hospital_id])
        @hospital = Hospital.find(session[:hospital_id])
    end
      private
        def doctor_params
          params.require(:doctor).permit(:doctor_name, :address, :department, :qualification,:hospital_name, :dob, :gender, :email, :password, :password_confirmation, :phone)
        end
        def set_doctor
    
          if session[:doctor_id]
            @doctor = Doctor.find(params[:id])
            # current.doctor = doctor.find_by(id: session[:doctor_id])   
            end
        end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:patient_id]
      @patient = Patient.find(session[:patient_id])
    end
    if session[:doctor_id]
      @doctor = Doctor.find(session[:doctor_id])
    end
    if session[:hospital_id]
      @hospital = Hospital.find(session[:hospital_id])
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
    @q = Doctor.ransack(params[:q])
    @doctors =  @q.result(distinct: true)
  end

  def new
    @patient = Patient.new
  end

  def login
    @patient = Patient.new
  end

  def logout
    session.delete(:patient_id)
     redirect_to :controller => 'home', :action => 'index'
  end

  def signin
    patient = Patient.find_by(email: params[:email])
       if patient.present? && patient.authenticate(params[:password])
        session[:patient_id] = patient.id
        redirect_to patient_path(patient), notice: "Logged in succesfully"
       else
        flash[:alert] = "Invalid email or password"
        render 'login'
       end
  end
  
  def prescription
    @patient = Patient.find(session[:patient_id])
    @prescriptions = Prescription.where(patient_id: session[:patient_id])
  end
  def doctorseeks
    @patient = Patient.find(session[:patient_id])
    @doctorseeks = Doctorseek.where(patient_id: session[:patient_id])
  end

  def previousrecords
    @patient = Patient.find(session[:patient_id])
    @previousrecords = Previousrecord.where(patient_id: session[:patient_id])
    
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      flash[:success] = "Patient successfully created"
      session[:patient_id] = @patient.id
      redirect_to @patient
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to root_path
  end

  private
  def patient_params
    params.require(:patient).permit(:patient_name, :address,:gender,:dob , :email, :password, :password_confirmation, :phone)
  end

  def set_patient
    
    if session[:patient_id]
      @patient = Patient.find(params[:id])
      # current.patient = Patient.find_by(id: session[:patient_id])   
      current = Patient.find(session[:patient_id])
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctorappoints_helper.rb
module DoctorappointsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/doctorseeks_helper.rb
module DoctorseeksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/patienttells_helper.rb
module PatienttellsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/previousrecords_helper.rb
module PreviousrecordsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/doctors/_form.html.erb
<%= form_with model: [ @hospital, @hospital.doctors.build ] do |form| %>
<div class="row">
    <div class="col-md-6">
  
    <%= form.text_field :doctor_name ,class:"form-control" ,placeholder:"Doctor name" %>
  </div>
  

  <div class="col-md-6">

    <%= form.text_field :address ,class:"form-control" ,placeholder:"address"%>
  </div>
</div>
</br>
<div class="row">
  <div class="col-md-6">
    
    <%= form.text_field :department ,class:"form-control" ,placeholder:"department" %>
  </div>

  <div class="col-md-6">
  
    <%= form.text_field :qualification ,class:"form-control" ,placeholder:"qualification"%>
  </div>
</div>  
<%= form.hidden_field :hospital_name, :value => @hospital.hospital_name %>
</br>
<div class="row">
  <div class="col-md-6">
    <%= form.label :dob %>
    <%= form.date_field :dob %>
  </div>

  <div class="col-md-6">
    Gender&nbsp;
    <%= form.radio_button :gender, 'Male' %> Male
    <%= form.radio_button :gender, 'Female' %> Female
  </div>
</div>    

<br>
<div class="row">
  <div class="col-md-6">

    <%= form.text_field :email ,class:"form-control" ,placeholder:"email"%>
  </div>

  <div class="col-md-6">

    
    <%= form.number_field :phone ,class:"form-control" ,placeholder:"phone number"%>
  </div>
</div>  
</br>
<div class="row">
  <div class="col-md-6">
   
    
    <%= form.password_field :password ,class:"form-control",placeholder:"password" %>
  </div>

  <div class="col-md-6">
    <%= form.password_field :password_confirmation ,class:"form-control",placeholder:"password confirmation "%>
    
  </div>
</div>
</br>
  <div class="actions text-center">
    <%= form.submit nil, class: 'btn btn-success' %>
   
  </div>
  </br>
<% end %>

app/views/doctors/doctordiagnosis.html.erb
<h1>hello doctor: <%= @doctor.doctor_name%></h1>
<%# <h1>Your Patient <%= @patient.patient_name%>
<%= link_to 'PreviousRecords', doctors_previousrecords_path  ,class:"btn btn-primary" %>

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      
      <th>patient_name</th>
      <th>symptoms</th>
      <th>seek details</th>
      <th>Prescription</th>
      <th>Delete</th>

    </tr>
  </thead>

  <tbody>
 <% @doctorappoints.each do |doctorappoint| %> 
      <tr>
        
        <td><%= doctorappoint.patientName %></td>
        <td><%= doctorappoint.notes %></td>
        <td><%= link_to 'Ask more', doctorseeks_path(:patient_id => doctorappoint.patient_id,:doctorappoint_id => doctorappoint.id) ,class:"btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Write prescription', prescriptions_path(:patient_id => doctorappoint.patient_id,:doctorappoint_id => doctorappoint.id) ,class:"btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Remove Record', doctorappoint, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger btn-sm"%></td>

      </tr>
  <% end %> 
  </tbody>
</table>

app/views/doctors/index.html.erb
 </br>
 </br>
 <h1>Doctors</h1>
 <table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      <th>Doctor name</th>
      <th>Address</th>
      <th>Department</th>
      <th>Qualification</th>
      <th>Dob</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.doctor_name %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.department %></td>
        <td><%= doctor.qualification %></td>
        <td><%= doctor.dob %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  
 

app/views/doctors/login.html.erb
<h1> Doctor Login </h1>
<%= form_with url: doctors_signin_path do |form| %>
 
 <div class="mb-3">
    <%= form.label :email%>
    <%= form.text_field :email, class:"form-control", placeholder:"email"%>
</div>    
<div class="mb-3">
    <%= form.label :password%>
    <%= form.password_field :password, class:"form-control", placeholder:"password"%>
</div>    
<div class="mb-3">
    <%= form.submit 'submit', class:"btn btn-primary"%>
</div>    
<% end %>

app/views/doctors/previousrecords.html.erb
<h1>hello patient: <%= @doctor.doctor_name%></h1>
<%# <h1>Your Patient <%= @patient.patient_name%></h1> 

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      
        <th>Patient Name</th>
        <th>Symptoms</th>
        <th>Doctor comment</th>   
        <th>Prescription</th>   

    </tr>
  </thead>

  <tbody>

       <% @previousrecords.each do |previousrecord| %> 
      <tr>
        
        <td><%= previousrecord.patient_name %></td>
        <td><%= previousrecord.symptoms %></td>
        <td><%= previousrecord.notes %></td>
        <td><%= link_to 'View Prescription',previousrecord.image,class:"btn btn-primary btn-sm"%></td> 
      

      </tr>
  <% end %>
  
  </tbody>
</table>

app/views/patients/_form.html.erb
<%= form_with model: patient do |form| %>
</br>
   <div class="field form-group">
    
    <%= form.text_field :patient_name  ,class:"form-control",placeholder:"patient name"%>
    <% patient.errors.full_messages_for(:patient_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
  <div class="field form-group">
   
    <%= form.text_field :address, class:"form-control" , placeholder:"address"%>
    <% patient.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
  <div class="field form-group">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
    <% patient.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
<div class="row">
<div class="col-md-6">
    <%= form.label :dob %>
    <%= form.date_field :dob %>
  </div>

  <div class="col-md-6">
    Gender&nbsp;
    <%= form.radio_button :gender, 'Male' %> Male
    <%= form.radio_button :gender, 'Female' %> Female
  </div>
  </div>
  </br>

<div class="row">
  <div class="col-md-6">

    <%= form.password_field :password, class:"form-control", placeholder:"password" %>
    <% patient.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="col-md-6 ">
 
    <%= form.password_field :password_confirmation , class:"form-control", placeholder:"password confirmation"%>
    <% patient.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  </div>
  </br>
  <div class="field form-group">
   
    <%= form.text_field :phone,  class:"form-control",placeholder:"phone"%>
    <% patient.errors.full_messages_for(:phone).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</br>
  <div class="actions text-center">
    <%= form.submit nil, class: 'btn btn-success' %>
     
  </div>
 
<% end %>

app/views/patients/_search_form.html.erb
<nav class="navbar navbar-dark bg-dark justify-content-between"  >
  <a class="navbar-brand"></a>
  <div class="row">
    <%= search_form_for(@q, url: patient_path(session[:patient_id]), method: :get) do |f| %>
  <%= f.search_field :doctor_name_or_department_or_hospital_name_cont,class:"form-control",type:"search", placeholder: 'Search doctor name' %>

  <%= f.submit "Search",class:"btn btn-outline-success my-2 btn-sm" %>
<% end %>
  </div>
</nav>

app/views/patients/doctorseeks.html.erb
<h1>hello patient: <%= @patient.patient_name%></h1>
<%# <h1>Your Patient <%= @patient.patient_name%></h1> 

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      
        <th>Doctor Name</th>
        <th>PatientName</th>
        <th>Notes</th>   
        <th>Prescription</th>    

    </tr>
  </thead>


  <tbody>

       <% @doctorseeks.each do |doctorseek| %> 
      <tr>
        
        <td><%= doctorseek.doctor_name %></td>
        <td><%= @patient.patient_name%></td>
        <td><%= doctorseek.notes %></td>

        <td><%= link_to 'Tell more detail',patienttells_path(:doctor_id => doctorseek.doctor_id,:doctorappoint_id =>doctorseek.doctorappoint_id) ,class:"btn btn-primary btn-sm"%></td> 


      </tr>
  <% end %>
  
  </tbody>
</table>

app/views/patients/edit.html.erb
<h1>Edit patient</h1>

<%= render "form", patient: @patient %>

app/views/patients/index.html.erb
</br>
<h1 class = "text-light text-center bg-dark">Patient List</h1>

<div class="patient_page">

<%= link_to "Add New Patient", new_patient_path ,class:"btn btn-secondary btn-lg" %>
</div>
<br>
  <%# <table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      <th>Pateint name</th>
      <th>Address</th>
      <th>Gender</th>
      <th>DOB</th>
      <th>Email</th>
      <th>Phone</th>
  
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <%# <tr>
        <td><%= patient.patient_name %>
        <%# <td><%= patient.address %>
        <%# <td><%= patient.gender</td> %> 
        <%# <td><%= patient.dob %>
        <%# <td><%= patient.email %>
        <%# <td><%= patient.phone %>
      <%# </tr> %>
    <%# <% end %> 
  <%# </tbody>
</table>  %>

app/views/patients/login.html.erb
<h1> Patient Login </h1>
<%= form_with url: signin_patients_path do |form| %>
 
<div class="mb-3">
    <%= form.label :email%>
    <%= form.text_field :email, class:"form-control", placeholder:"email"%>
</div>    
<div class="mb-3">
    <%= form.label :password%>
    <%= form.password_field :password, class:"form-control", placeholder:"password"%>
</div>    
<div class="mb-3">
    <%= form.submit 'submit', class:"btn btn-primary"%>
</div>    
<% end %>

app/views/patients/new.html.erb
</br>
<h1 class = "text-light text-center bg-secondary">Add New Patient</h1>


<%= render "form", patient: @patient %>

app/views/patients/prescription.html.erb
<h1>hello patient: <%= @patient.patient_name%></h1>
<%# <h1>Your Patient <%= @patient.patient_name%></h1> 

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      
        <th>Doctor id</th>
        <th>PatientName</th>
        <th>Notes</th>   
        <th>Prescription</th>   
        <th>Delete</th>   

    </tr>
  </thead>


  <tbody>

       <% @prescriptions.each do |prescription| %> 
      <tr>
        
        <td><%= prescription.doctorName %></td>
        <td><%= @patient.patient_name%></td>
        <td><%= prescription.notes %></td>
        <%# <td><%= image_tag(prescription.image,style:'width:10%')%>
        <%# <td><%= link_to 'Download',prescription.image,download:''%>
        <td><%= link_to 'View Prescription',prescription.image,class:"btn btn-primary btn-sm"%></td> 
        <td><%= link_to 'Remove Record', prescription, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger btn-sm"%></td>

      </tr>
  <% end %>
  
  </tbody>
</table>

app/views/patients/previousrecords.html.erb
<h1>hello patient: <%= @patient.patient_name%></h1>
<%# <h1>Your Patient <%= @patient.patient_name%></h1> 

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      
        <th>Doctor Name</th>
        <th>Symptoms</th>
        <th>Doctor comment</th>   
        <th>Prescription</th>   

    </tr>
  </thead>

  <tbody>

       <% @previousrecords.each do |previousrecord| %> 
      <tr>
        
        <td><%= previousrecord.doctorName %></td>
        <td><%= previousrecord.symptoms %></td>
        <td><%= previousrecord.notes %></td>
        <td><%= link_to 'View Prescription',previousrecord.image,class:"btn btn-primary btn-sm"%></td> 
      

      </tr>
  <% end %>
  
  </tbody>
</table>

app/views/patients/show.html.erb
<h1 class = "text-dark text-center bg-light" ><%= @patient.patient_name %> </h1>

<%# <nav class="navbar navbar-dark bg-dark justify-content-between"  >
  <a class="navbar-brand">Navbar</a>
  <div class="row">
    <input class="form-control " type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 btn-sm" type="submit">Search</button>
  </div>
</nav> %>
<br>
<%= link_to 'Prescription', patients_prescription_path  ,class:"btn btn-primary" %>&nbsp;
<%= link_to 'PreviousRecords', patients_previousrecords_path  ,class:"btn btn-primary" %>&nbsp;
<%= link_to 'Edit profile', edit_patient_path(@patient.id)  ,class:"btn btn-primary" %>
<%= link_to 'Doctor seek Details', patients_doctorseeks_path  ,class:"btn btn-primary" %>
<br>
<%= render 'patients/search_form.html.erb'%>
<h1 class = "text-dark text-center bg-light">Doctor List </h1>

 <table class="table table-striped table-hover table-bordered table-sm">
  <thead class="table-dark">
    <tr>
      
      <th>Hospital name</th>
      <th>Doctor name</th>
      <th>Address</th>
      <th>Department</th>
      <th>Qualification</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Appoint</th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        
        <td><%= doctor.hospital_name %></td>
        <td><b>Dr.&nbsp;</b><%= doctor.doctor_name %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.department %></td>
        <td><%= doctor.qualification %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.phone %></td>
        <td><%= link_to 'Symptoms', doctorappoints_path(:doctor_id => doctor.id) ,class:"btn btn-primary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>